### ISSUE TITLE
The navigation bar does not use the Dynamic Color pallet

### ISSUE THREAD

**Issue by QuietKeyStroke** [jaamesokhan/jaamesokhan-client#182]
This issue is related to this PR: https://github.com/jaamesokhan/jaamesokhan-client/pull/180

![Screenshot_20241212_223132_ .jpg](https://github.com/user-attachments/assets/273001cd-bd6e-4d65-95b8-69e3df416d0e)

**Comment by QuietKeyStroke** [comment]
This might help:

https://developer.android.com/design/ui/mobile/guides/foundations/system-bars

**Comment by MuhammadKhosravi** [comment]
Thanks for your interest in Jaame-Sokhan. 
Currently we are redesigning and rewriting the whole application. So, unfortunately we don't think we can merge this right now, or maybe even later, because it does not keep the visual identity of the application. So we prefer to have only two fixed themes, at least for now.
But we appreciate your work and hope you to contribute to project after the upcoming redesign.
